-- Apply once to existing projects. Included in schema.sql for new projects.
create table public.chart_of_accounts (
 code text primary key,
 name text not null,
 account_type text not null,
 parent_code text references public.chart_of_accounts(code),
 is_posting boolean not null
);
alter table public.chart_of_accounts enable row level security;
revoke all on public.chart_of_accounts from anon, authenticated;
grant select on public.chart_of_accounts to authenticated;
create policy "Authenticated users read account definitions" on public.chart_of_accounts for select to authenticated using (true);
insert into public.chart_of_accounts(code,name,account_type,parent_code,is_posting) values
('1000','Cash & Bank','Asset',null,false),
('1001','Cash on Hand','Asset','1000',true),
('1002','Business Bank Account','Asset','1000',true),
('1003','Petty Cash','Asset','1000',true),
('1100','Accounts Receivable','Asset',null,false),
('1101','Customer Receivables','Asset','1100',true),
('1200','Inventory / Materials','Asset',null,false),
('1201','Raw Material - Mild Steel','Asset','1200',true),
('1202','Raw Material - Stainless Steel','Asset','1200',true),
('1203','Raw Material - Aluminium','Asset','1200',true),
('1204','Work in Progress','Asset','1200',true),
('1205','Finished Goods','Asset','1200',true),
('1300','Fixed Assets','Asset',null,false),
('1301','CNC Laser Machine','Asset','1300',true),
('1302','Air Compressor','Asset','1300',true),
('1303','Chiller','Asset','1300',true),
('1304','Gas System','Asset','1300',true),
('1305','Material Handling Equipment','Asset','1300',true),
('1306','Computers / CAD Workstations','Asset','1300',true),
('1307','Workshop Tools','Asset','1300',true),
('1308','Furniture','Asset','1300',true),
('1400','Accumulated Depreciation','Contra asset',null,false),
('1401','Laser Machine Depreciation','Contra asset','1400',true),
('1402','Equipment Depreciation','Contra asset','1400',true),
('1403','Vehicle Depreciation','Contra asset','1400',true),
('1404','Computer Depreciation','Contra asset','1400',true),
('2000','Accounts Payable','Liability',null,false),
('2001','Steel Suppliers','Liability','2000',true),
('2002','Gas Suppliers','Liability','2000',true),
('2003','Consumable Suppliers','Liability','2000',true),
('2004','Service Contractors','Liability','2000',true),
('2100','Customer Advances','Liability',null,false),
('2101','Customer Advances / Deposits','Liability','2100',true),
('2200','VAT / Tax Control','Tax control',null,false),
('2201','VAT Input','Tax control','2200',true),
('2202','VAT Output','Tax control','2200',true),
('2203','VAT Payable / Receivable','Tax control','2200',true),
('3000','Owner Capital','Equity',null,false),
('3001','Owner Capital Contributions','Equity','3000',true),
('3002','Owner Drawings','Equity','3000',true),
('3003','Retained Earnings','Equity','3000',true),
('4000','Laser Cutting Sales','Revenue',null,false),
('4001','Laser Cutting Revenue','Revenue','4000',true),
('4100','Design & Fabrication Sales','Revenue',null,false),
('4101','Design / CAD Charges','Revenue','4100',true),
('4102','Fabrication / Bending Charges','Revenue','4100',true),
('4200','Material Sales','Revenue',null,false),
('4201','Material Supply Revenue','Revenue','4200',true),
('4300','Other Income','Revenue',null,false),
('4301','Delivery Revenue','Revenue','4300',true),
('4302','Scrap Sales','Revenue','4300',true),
('4303','Gain on Asset Sale','Revenue','4300',true),
('4304','Other Income','Revenue','4300',true),
('5000','Material Cost','Direct cost',null,false),
('5001','Material Consumed on Jobs','Direct cost','5000',true),
('5100','Job Consumables','Direct cost',null,false),
('5101','Assist Gas - Oxygen','Direct cost','5100',true),
('5102','Assist Gas - Nitrogen','Direct cost','5100',true),
('5103','Nozzles / Lenses','Direct cost','5100',true),
('5104','Other Direct Consumables','Direct cost','5100',true),
('5200','Direct Job Costs','Direct cost',null,false),
('5201','Direct Labour','Direct cost','5200',true),
('5202','Outsourced Bending / Fabrication','Direct cost','5200',true),
('5203','Job-Specific Transport','Direct cost','5200',true),
('6000','Workshop Expenses','Expense',null,false),
('6001','Workshop Rent','Expense','6000',true),
('6002','Electricity','Expense','6000',true),
('6003','Machine Maintenance','Expense','6000',true),
('6004','Spare Parts','Expense','6000',true),
('6005','PPE & Safety Equipment','Expense','6000',true),
('6006','Cleaning','Expense','6000',true),
('6007','Insurance','Expense','6000',true),
('6100','Salaries & Staff Costs','Expense',null,false),
('6101','Administration Salaries','Expense','6100',true),
('6102','Overtime','Expense','6100',true),
('6103','Other Staff Costs','Expense','6100',true),
('6200','Office & Admin Expenses','Expense',null,false),
('6201','Internet / Telephone','Expense','6200',true),
('6202','Software / CAD Subscription','Expense','6200',true),
('6203','Printing / Stationery','Expense','6200',true),
('6204','Accounting / Professional Fees','Expense','6200',true),
('6205','Advertising / Marketing','Expense','6200',true),
('6206','Sales Commission','Expense','6200',true),
('6207','Customer Entertainment','Expense','6200',true),
('6208','Other Government Fees','Expense','6200',true),
('6209','Other Administration','Expense','6200',true),
('6300','Vehicle & Delivery Expenses','Expense',null,false),
('6301','Fuel','Expense','6300',true),
('6302','Vehicle Repairs','Expense','6300',true),
('6303','Courier / Delivery','Expense','6300',true),
('6400','Bank & Finance Charges','Expense',null,false),
('6401','Bank Charges','Expense','6400',true),
('6402','Finance Charges','Expense','6400',true),
('6500','Depreciation','Expense',null,false),
('6501','Laser Machine Depreciation Expense','Expense','6500',true),
('6502','Equipment Depreciation Expense','Expense','6500',true),
('6503','Vehicle Depreciation Expense','Expense','6500',true),
('6504','Computer Depreciation Expense','Expense','6500',true),
('6600','Other Expenses','Expense',null,false),
('6601','Loss on Asset Sale','Expense','6600',true);
alter table public.business_records add column account_code text references public.chart_of_accounts(code);
create function public.validate_expense_account() returns trigger language plpgsql set search_path=public as $$
declare selected public.chart_of_accounts;
begin
 if new.account_code is null then return new; end if;
 if new.kind <> 'expense' then raise exception 'Account classification is currently supported for expenses only'; end if;
 select * into selected from public.chart_of_accounts where code=new.account_code;
 if not found or not selected.is_posting then raise exception 'Select a posting sub-account'; end if;
 if new.category='Capital expense' and selected.parent_code<>'1300' then raise exception 'Select a fixed asset sub-account for capital expenses'; end if;
 if new.category<>'Capital expense' and selected.account_type not in ('Expense','Direct cost') then raise exception 'Select an expense or direct cost sub-account'; end if;
 return new;
end $$;
create trigger validate_expense_account before insert or update on public.business_records for each row execute function public.validate_expense_account();
